from __future__ import annotations

import argparse
import math
from pathlib import Path

import pandas as pd
import yaml

ROW_END = " \\\\"


def esc(text: object) -> str:
    return (
        str(text)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def model_tex(model: str) -> str:
    return r"\texttt{" + esc(model) + "}"


def fmt(value: object, digits: int = 3) -> str:
    try:
        x = float(value)
    except (TypeError, ValueError):
        return "TBD"
    if not math.isfinite(x):
        return "--"
    return f"{x:.{digits}f}"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {path}")


def configured_models(path: Path) -> list[str]:
    cfg = yaml.safe_load(path.read_text(encoding="utf-8"))
    return [str(row["id"]) for row in cfg["models"]]


def rq1_table(summary: pd.DataFrame, models: list[str]) -> str:
    rows: list[str] = []
    for model in models:
        sub = summary[summary["model"] == model]
        if sub.empty:
            vals = ["TBD"] * 9
        else:
            r = sub.iloc[0]
            vals = [
                fmt(r.get("acc_A")),
                fmt(r.get("acc_B")),
                fmt(r.get("acc_C")),
                fmt(r.get("acc_D")),
                fmt(r.get("TBR_C")),
                fmt(r.get("Delta_AA")),
                fmt(r.get("SUR")),
                fmt(r.get("TOR@0.80")),
                fmt(r.get("ECE")),
            ]
        rows.append(model_tex(model) + " & " + " & ".join(vals) + ROW_END)
    body = "\n".join(rows)
    return rf"""% AUTO-GENERATED by scripts/make_paper_tables.py. Do not edit numbers manually.
\begin{{table*}}[t]
\centering
\scriptsize
\begin{{tabular}}{{@{{}}lccccccccc@{{}}}}
\toprule
Model & Acc A & Acc B & Acc C & Acc D & TBR$\downarrow$ & $\Delta_{{AA}}\uparrow$ & SUR$\uparrow$ & TOR$.80\downarrow$ & ECE$\downarrow$ \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{RQ1 primary results generated from the audited neutral deterministic run. Brier, NLL, ADG, classwise ECE, and verb-cluster 95\% intervals are emitted in companion CSV/LaTeX artifacts.}}
\label{{tab:rq1}}
\end{{table*}}"""


def rq1_ci_table(bootstrap: pd.DataFrame, models: list[str]) -> str:
    metrics = ["acc_C", "TBR_C", "Delta_AA", "SUR", "TOR@0.80", "ADG"]
    rows: list[str] = []
    for model in models:
        for metric in metrics:
            sub = bootstrap[
                (bootstrap["model"] == model) & (bootstrap["metric"] == metric)
            ]
            if sub.empty:
                estimate = ci = "TBD"
            else:
                r = sub.iloc[0]
                estimate = fmt(r.get("estimate"))
                ci = f"[{fmt(r.get('ci_low'))}, {fmt(r.get('ci_high'))}]"
            rows.append(
                f"{model_tex(model)} & {esc(metric)} & {estimate} & {ci}" + ROW_END
            )
    body = "\n".join(rows)
    return rf"""% AUTO-GENERATED. Companion interval table; include if space permits.
\begin{{table*}}[t]
\centering
\scriptsize
\begin{{tabular}}{{@{{}}llcc@{{}}}}
\toprule
Model & Metric & Estimate & 95\% verb-cluster bootstrap CI \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{Predeclared verb-cluster bootstrap intervals for key RQ1 quantities.}}
\label{{tab:rq1-ci}}
\end{{table*}}"""


def rq2_table(ranking: pd.DataFrame, models: list[str]) -> str:
    labels = {
        "1-maxprob": r"$1-\max p$",
        "predictive_entropy": "Pred. entropy",
        "sampling_variation_ratio": "Sampling variation",
        "sampling_label_entropy": "Sampling entropy",
    }
    rows: list[str] = []
    if not ranking.empty and "scope" in ranking.columns:
        all_scope = ranking[ranking["scope"] == "all"]
    else:
        all_scope = ranking
    for model in models:
        for signal, label in labels.items():
            if all_scope.empty:
                sub = all_scope
            else:
                sub = all_scope[
                    (all_scope["model"] == model) & (all_scope["signal"] == signal)
                ]
            if sub.empty:
                vals = ["TBD", "TBD", "TBD"]
            else:
                r = sub.iloc[0]
                vals = [
                    fmt(r.get("error_AUROC")),
                    fmt(r.get("error_AUPRC")),
                    fmt(r.get("E_AURC")),
                ]
            rows.append(
                f"{model_tex(model)} & {label} & " + " & ".join(vals) + ROW_END
            )
    body = "\n".join(rows)
    return rf"""% AUTO-GENERATED. All four predeclared signals are shown; no best-signal selection.
\begin{{table*}}[t]
\centering
\scriptsize
\begin{{tabular}}{{@{{}}llccc@{{}}}}
\toprule
Model & Signal & Error AUROC$\uparrow$ & Error AUPRC$\uparrow$ & E-AURC$\downarrow$ \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{RQ2 uncertainty-faithfulness results on all examples. Group-C-only rankings are generated in the processed artifact and reported when space permits.}}
\label{{tab:rq2}}
\end{{table*}}"""


def rq2_ci_table(ranking_bootstrap: pd.DataFrame, models: list[str]) -> str:
    labels = {
        "1-maxprob": r"$1-\max p$",
        "predictive_entropy": "Pred. entropy",
        "sampling_variation_ratio": "Sampling variation",
        "sampling_label_entropy": "Sampling entropy",
    }
    rows: list[str] = []
    if ranking_bootstrap.empty:
        base = ranking_bootstrap
    else:
        base = ranking_bootstrap[
            (ranking_bootstrap["scope"] == "all")
            & (ranking_bootstrap["metric"] == "error_AUROC")
        ]
    for model in models:
        for signal, label in labels.items():
            sub = base[
                (base["model"] == model) & (base["signal"] == signal)
            ] if not base.empty else base
            if sub.empty:
                estimate = ci = "TBD"
            else:
                r = sub.iloc[0]
                estimate = fmt(r.get("estimate"))
                ci = f"[{fmt(r.get('ci_low'))}, {fmt(r.get('ci_high'))}]"
            rows.append(
                f"{model_tex(model)} & {label} & {estimate} & {ci}" + ROW_END
            )
    body = "\n".join(rows)
    return rf"""% AUTO-GENERATED. Companion RQ2 interval table; include if space permits.
\begin{{table*}}[t]
\centering
\scriptsize
\begin{{tabular}}{{@{{}}llcc@{{}}}}
\toprule
Model & Signal & Error AUROC & 95\% verb-cluster bootstrap CI \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{Verb-cluster bootstrap intervals for the primary RQ2 error-ranking statistic. Undefined intervals are shown as -- when a resample lacks both error classes.}}
\label{{tab:rq2-ci}}
\end{{table*}}"""


def rq3_table(recheck: pd.DataFrame, models: list[str], config: dict) -> str:
    signal = str(config["selective"]["primary_recheck_signal"])
    threshold = float(config["selective"]["primary_recheck_threshold"])
    policies = [
        ("base_neutral", "Base neutral"),
        ("blanket_verifier", "Blanket verifier"),
        ("selective_recheck", f"Selective {signal} @ {threshold:.2f}"),
    ]
    rows: list[str] = []
    for model in models:
        for policy, display in policies:
            if recheck.empty:
                sub = recheck
            else:
                sub = recheck[
                    (recheck["model"] == model) & (recheck["policy"] == policy)
                ]
            if policy == "selective_recheck" and not sub.empty:
                sub = sub[
                    (sub["signal"] == signal)
                    & ((sub["threshold"] - threshold).abs() < 1e-12)
                ]
            if sub.empty:
                vals = ["TBD", "TBD", "TBD", "TBD", "TBD"]
            else:
                r = sub.iloc[0]
                vals = [
                    fmt(r.get("risk")),
                    fmt(r.get("TBR_C")),
                    fmt(r.get("group_D_accuracy")),
                    fmt(r.get("recheck_rate")),
                    fmt(r.get("incremental_token_ratio")),
                ]
            rows.append(
                f"{model_tex(model)} & {esc(display)} & "
                + " & ".join(vals)
                + ROW_END
            )
    body = "\n".join(rows)
    return rf"""% AUTO-GENERATED. The selective operating point is frozen in configs/experiment.yaml.
\begin{{table*}}[t]
\centering
\scriptsize
\begin{{tabular}}{{@{{}}llccccc@{{}}}}
\toprule
Model & Policy & Risk$\downarrow$ & TBR$\downarrow$ & D Acc$\uparrow$ & Recheck & Added tokens/base \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\caption{{RQ3 base, blanket-verifier, and predeclared selective-recheck operating point. Full threshold sweeps remain available in the processed artifact and figures.}}
\label{{tab:rq3}}
\end{{table*}}"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--summary", type=Path, required=True)
    p.add_argument("--bootstrap", type=Path, required=True)
    p.add_argument("--ranking", type=Path, required=True)
    p.add_argument("--ranking-bootstrap", type=Path, required=True)
    p.add_argument("--recheck", type=Path, required=True)
    p.add_argument("--models", type=Path, default=Path("configs/models.yaml"))
    p.add_argument("--config", type=Path, default=Path("configs/experiment.yaml"))
    p.add_argument("--outdir", type=Path, default=Path("paper/generated"))
    args = p.parse_args()

    models = configured_models(args.models)
    config = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    summary = pd.read_csv(args.summary)
    bootstrap = pd.read_csv(args.bootstrap)
    ranking = pd.read_csv(args.ranking)
    ranking_bootstrap = pd.read_csv(args.ranking_bootstrap)
    recheck = pd.read_csv(args.recheck)

    write(args.outdir / "rq1_table.tex", rq1_table(summary, models))
    write(args.outdir / "rq1_ci_table.tex", rq1_ci_table(bootstrap, models))
    write(args.outdir / "rq2_table.tex", rq2_table(ranking, models))
    write(args.outdir / "rq2_ci_table.tex", rq2_ci_table(ranking_bootstrap, models))
    write(args.outdir / "rq3_table.tex", rq3_table(recheck, models, config))


if __name__ == "__main__":
    main()
